name: Deploy React App to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Triggered by'
        default: 'Manual'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/cache
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Build React App
        run: yarn build
        env:
          HTTPS: 'true'
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Done
        run: echo "Deployed by ${{ inputs.name }}"
